version: '3.9'

services:
  nginx:
    ports:
      - "80:80"
  api:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production

    command: node app.js