version: '3.9'

services:
  nginx:
    ports:
      - "80:80"

  api:
    # this command is related to docker swarn
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY = ${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET = ${CLOUDINARY_SECRET}
      - MAPBOX_TOKEN = ${MAPBOX_TOKEN}
      - GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET = ${GOOGLE_CLIENT_SECRET}
      - NODE_ENV=development
      
      

    command: node app.js