version: '3.9'

services:
  nginx:
    ports:
      - "80:80"
  api:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY = ${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET = ${CLOUDINARY_SECRET}
      - MAPBOX_TOKEN = ${MAPBOX_TOKEN}
      - GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET = ${GOOGLE_CLIENT_SECRET}

    command: node app.js