version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # links:
    #   - api
    

  mongo_db:
    container_name: db_container_stayease
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  # redis:
  #   image: redis
    
  api:
    build: .
    # image: sachinjss/stayease-api
    environment:
      - PORT=3000
    
    depends_on:
      - mongo_db
      
    

      

volumes:
  mongo_db: {}
