version: '3.9'

services:
  nginx:
    ports:
      - "80:80"
  api:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY = ${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET = ${CLOUDINARY_SECRET}
      - MAPBOX_TOKEN = ${MAPBOX_TOKEN}
      - GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET = ${GOOGLE_CLIENT_SECRET}
      # - NODE_ENV=development
      # - CLOUDINARY_CLOUD_NAME = dzp4ziyue
      # - CLOUDINARY_KEY = 491168893643126
      # - CLOUDINARY_SECRET = hWDslDG__M4kXuWOiyD6EEcT6Nc
      # - MAPBOX_TOKEN = pk.eyJ1Ijoic2FjaGluNTMiLCJhIjoiY2xteDhycmIyMDd3MDJrcXkzcGhjbTBpcCJ9.mPeSSH07Ft3gwK59uwYjMA
      # - GOOGLE_CLIENT_ID = 176726329187-8vppverausfkc6lnmam96b2riue17kg4.apps.googleusercontent.com
      # - GOOGLE_CLIENT_SECRET = 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

    command: node app.js